// -*- C++ -*-
//
// generated by wxGlade 0.9.9pre on Sat Sep  7 20:50:03 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGLADE_OUT_H
#define WXGLADE_OUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: MyFrame::attributes
    wxNotebook* notebook_1;
    wxPanel* notebook_1_pane_1;
    wxListBox* list_box_1;
    wxButton* button_1;
    wxButton* button_2;
    wxPanel* notebook_1_Logactivity;
    wxTextCtrl* text_ctrl_1;
    wxPanel* notebook_1_General;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGLADE_OUT_H
