name: netvfy-agent
version: 1.0.2
summary: Netvfy - Connect to your secure virtual network.
description: |
  Netvfy - Connect to your secure virtual network.

  This snap contains the Netvfy agent.

confinement: strict
grade: stable
base: core18

apps:
  netvfy-agent:
    command: netvfy-agent
    plugs:
      - network
      - network-bind
      - network-control

parts:
  netvfy-agent:
    plugin: cmake
    source: .
    source-type: git
    build-packages:
      - build-essential
      - scons
      - cmake
      - libevent-dev
      - libssl-dev
      - libjansson-dev
      - libcurl4-openssl-dev
    stage-packages:
      - libevent-2.1-6
      - libevent-core-2.1-6
      - libevent-extra-2.1-6
      - libevent-openssl-2.1-6
      - libjansson4
      - libcurl4
    override-build: |
      cd $SNAPCRAFT_PART_SRC/tapcfg/
      ./buildall.sh || true
      cd -
      snapcraftctl build
