FROM debian:stretch

RUN apt-get update -qq && apt-get install -yq --no-install-recommends ca-certificates curl scons cmake build-essential mingw-w64 nsis unzip p7zip-full wget

ENV LIBJANSSON_VERSION 2.12
ENV LIBJANSSON_URL "http://www.digip.org/jansson/releases/jansson-${LIBJANSSON_VERSION}.tar.bz2"
RUN curl "${LIBJANSSON_URL}" | tar xjf - -C /usr/src
WORKDIR "/usr/src/jansson-${LIBJANSSON_VERSION}"
RUN CC=i686-w64-mingw32-gcc CPPFLAGS=-D__MINGW_USE_VC2005_COMPAT ./configure --host=i686-w64-mingw32
RUN make

ENV LIBRESSL_VERSION 2.9.2
ENV LIBRESSL_URL "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${LIBRESSL_VERSION}.tar.gz"
RUN curl "${LIBRESSL_URL}" | tar xzf - -C /usr/src
WORKDIR "/usr/src/libressl-${LIBRESSL_VERSION}"
RUN CC=i686-w64-mingw32-gcc CPPFLAGS=-D__MINGW_USE_VC2005_COMPAT ./configure --host=i686-w64-mingw32
RUN make

ENV LIBEVENT_VERSION 2.0.22
ENV LIBEVENT_URL "https://github.com/libevent/libevent/releases/download/release-${LIBEVENT_VERSION}-stable/libevent-${LIBEVENT_VERSION}-stable.tar.gz"
RUN curl -L "${LIBEVENT_URL}" | tar xzf - -C /usr/src
WORKDIR "/usr/src/libevent-${LIBEVENT_VERSION}-stable"
RUN CC=i686-w64-mingw32-gcc CPPFLAGS="-D__MINGW_USE_VC2005_COMPAT" ./configure --host=i686-w64-mingw32 \
                CPPFLAGS="-I/usr/src/libressl-${LIBRESSL_VERSION}/include/" \
                LDFLAGS="-L/usr/src/libressl-${LIBRESSL_VERSION}/ssl/.libs/ -L/usr/src/libressl-${LIBRESSL_VERSION}/crypto/.libs/"
RUN make

ENV LIBCURL_VERSION "7.65.3"
ENV LIBCURL_URL "https://curl.haxx.se/download/curl-${LIBCURL_VERSION}.tar.gz"
RUN curl "${LIBCURL_URL}" | tar xzf - -C /usr/src
WORKDIR "/usr/src/curl-${LIBCURL_VERSION}"
RUN CC=i686-w64-mingw32-gcc ./configure --host=i686-w64-mingw32 --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-proxy --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher \
		CPPFLAGS="-I/usr/src/libressl-${LIBRESSL_VERSION}/include/" \
                LDFLAGS="-L/usr/src/libressl-${LIBRESSL_VERSION}/ssl/.libs/ -L/usr/src/libressl-${LIBRESSL_VERSION}/crypto/.libs/"
RUN make
RUN make ca-bundle

ENV WX_VERSION "3.1.2"
ENV LIBWX_FILE "wxMSW-${WX_VERSION}_gcc810_Dev.7z"
ENV HWX_FILE "wxWidgets-${WX_VERSION}-headers.7z"
ENV LIBWX_URL "https://github.com/wxWidgets/wxWidgets/releases/download/v${WX_VERSION}/${LIBWX_FILE}"
ENV HWX_URL "https://github.com/wxWidgets/wxWidgets/releases/download/v${WX_VERSION}/${HWX_FILE}"
RUN wget "${LIBWX_URL}"
RUN 7z x ${LIBWX_FILE} -o/usr/src/wx
RUN wget "${HWX_URL}"
RUN 7z x ${HWX_FILE} -o/usr/src/wx
RUN cp /usr/src/wx/include/wx/msw/setup.h /usr/src/wx/include/wx/setup.h
RUN rm ${LIBWX_FILE} ${HWX_FILE}

CMD true && \
    cp -r /usr/src/netvfy-agent/tapcfg /usr/src/tapcfg && \
    cd /usr/src/tapcfg && \
    rm -rf build && \
    scons --force-mingw32 && \
    mkdir -p /usr/src/netvfy-build.windows.cli && \
    cd /usr/src/netvfy-build.windows.cli && \
    cmake -DCMAKE_TOOLCHAIN_FILE=win32/toolchain-mingw32.cmake \
	  -DWX_ROOT_DIR="/usr/src/wx" \
          -DLIBRESSL_ROOT_DIR="/usr/src/libressl-${LIBRESSL_VERSION}" \
          -DLIBJANSSON_ROOT_DIR="/usr/src/jansson-${LIBJANSSON_VERSION}" \
          -DLIBEVENT_ROOT_DIR="/usr/src/libevent-${LIBEVENT_VERSION}-stable" \
          -DLIBCURL_ROOT_DIR="/usr/src/curl-${LIBCURL_VERSION}" \
          -DTAPCFG_ROOT_DIR="/usr/src/tapcfg" \
          -DCROSS_COMPILER="i686-w64-mingw32" \
          -DWITH_GUI="yes" \
          ../netvfy-agent && \
    make netvfy-agent VERBOSE=1 && \
    makensis -DLIBWX_PATH="/usr/src/wx" \
	     -DLIBRESSL_PATH="/usr/src/libressl-${LIBRESSL_VERSION}" \
             -DLIBEVENT_PATH="/usr/src/libevent-${LIBEVENT_VERSION}-stable" \
             -DLIBCURL_PATH="/usr/src/curl-${LIBCURL_VERSION}" \
             -DLIBJANSSON_PATH="/usr/src/jansson-${LIBJANSSON_VERSION}" \
             -DTAPCFG_PATH="/usr/src/tapcfg" \
             -DMINGW_PATH="/usr/lib/gcc/i686-w64-mingw32/6.3-win32" \
             -DBDIR="${PWD}" \
             -DOUTFILE="/tmp/netvfy-agent-gui_x86.exe" \
             ../netvfy-agent/win32/package_win32.nsi && \
    true
